parameters:
    # ...
    symmetry_factory.class: Mobile\SymmetryBundle\Symmetry\SymmetryFactory
    
services:
    symmetry_manager:
        class:          %symmetry_factory.class%
        arguments:      []
